config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  resources :categories, param: :slug
  resources :posts,  param: :slug
  root 'mainpages#index'
  get 'homepage', to: 'mainpages#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :posts, dependent: :destroy
  validates :title, presence: true
  before_create { self.slug = SecureRandom.hex(6) }

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :title, presence: true
  validates :body, presence: true
  validates :title, length: {maximum: 50}
  before_create { self.slug = SecureRandom.hex(6) }


  def self.search(search)
    where("body LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :categories, dependent: :destroy
  has_and_belongs_to_many :categories

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find_by(slug: params[:slug])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    begin
        @category.users << current_user
    rescue
      redirect_to new_user_session_path
      return
    end
    if @category.save
      redirect_to category_path(@category.slug)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    begin
    @category = current_user.categories.find_by!(slug: params[:slug])
    rescue
      redirect_to root_path
    end
  end

  def update
    begin
    @category = current_user.categories.find_by!(slug: params[:slug])
    rescue
      redirect_to root_path
      return
    end
    if @category.update(category_params)
      redirect_to category_path(@category.slug)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    begin
        @category = current_user.categories.find_by!(slug: params[:slug])
    rescue
      redirect_to root_path
      return
    end
    @category.destroy
    redirect_to root_path, status: :see_other
  end


  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/mainpages_controller.rb
class MainpagesController < ApplicationController
  def index
    @users = User.all
    @new_posts = Post.all.order("updated_at DESC")
    @new_category = Category.new
    if current_user.present?
        @user_posts = current_user.posts.order("updated_at DESC").first(10)
    end
  end

  def homepage
    @posts = Post.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    if params[:post_search]
      @post_search_result= Post.search(params[:post_search]).order("created_at DESC")
    elsif params[:category_search]
      @category_search_result = Category.search(params[:category_search]).order("created_at DESC")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find_by(slug: params[:slug])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    category_id = params[:current_user][:category_id]
    begin
    @post.category_id = Category.find(category_id).id
    @post.user_id = current_user.id
    rescue
      render :new
      return
    end

    if @post.save
      redirect_to post_path(@post.slug)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    begin
      @post = current_user.posts.find_by!(slug: params[:slug])
    rescue
      redirect_to root_path
    end
  end

  def update
    begin
      @post = current_user.posts.find_by!(slug: params[:slug])
      @post.category_id = current_user.categories.find(params[:post][:category_id]).id
      @post.user_id = current_user.id
    rescue
      redirect_to root_path
      return
    end
    if @post.update(post_params)
      redirect_to post_path(@post.slug)
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def show
    @post = Post.find_by(slug: params[:slug])
  end

  def destroy
    begin
      @post = current_user.posts.find_by!(slug: params[:slug])
    rescue
      redirect_to root_path
    end
    @post.destroy
    redirect_to root_path, status: :see_other
  end
  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/categories/_category.html.erb
<div>
<%= link_to category.title, category_path(category.slug), class: "text-xl text-orange-600 border-b-2 rounded border-gray-600" %>

</div>

app/views/categories/edit.html.erb
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-green-700">Edit Category</h2>
    </div>
    <div class="mt-8 space-y-6">
    <%= form_with model: @category, url: category_path(@category.slug) do |f| %>
      <div class="rounded-md shadow-sm -space-y-px">
          <%= f.text_field :title, autofocus: true, required: true, value: @category.title,  class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-sm", placeholder: "Title" %>
      </div>
      <div class="actions">
          <%= f.submit "Edit", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 mt-5" %>
        </div>
      <%end%>
      </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-green-700">Add Category</h2>
    </div>
    <div class="mt-8 space-y-6">
    <%= form_with model: @category do |f| %>
      <div class="rounded-md shadow-sm -space-y-px">
          <%= f.text_field :title, autofocus: true, autocomplete: "title", required: true, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-sm", placeholder: "Category Title" %>
      </div>
      <% @category.errors.full_messages_for(:title).each do |msg| %>
        <div> <%= msg %> </div>
      <% end %>
      <div class="actions">
          <%= f.submit "Create Category", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 mt-5" %>
        </div>
      <%end%>
      </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="flex mt-6 max-w-7xl mx-auto px-4 sm:px-6">
  <div class="flex-1 text-left">
    <h2 class="text-3xl  font-extrabold text-green-700">Category - <%= link_to @category.title, category_path(@category.slug), class:"border-2 border-b-current font-extrabold text-orange-600" %> </h2>
    <div class="grid grid-cols-1 mt-6">
      <h2 class="text-2xl font-extrabold text-green-700">Posts: </h2>
        <%= render partial: "posts/post", collection: @category.posts %>
    </div>
  </div>

<div class="ml-2">
  <%= link_to "Edit Category", edit_category_path(@category.slug), class:"whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-orange-600 hover:bg-orange-700"%>
  <%= link_to "Remove Category", category_path(@category.slug), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-orange-700 hover:bg-orange-900"%>
  <%= link_to "Add Post", new_post_path, class:"whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-orange-700 hover:bg-orange-900"%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HobNetwork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-gray-200">
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="relative">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex justify-between items-center border-b-2 border-amber-700 py-6 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <a href="/">
          <span class="mt-6 text-center text-3xl font-extrabold text-green-700"> Hobby Network </span>
        </a>
      </div>
      <nav class="hidden md:flex space-x-10">
      </nav>
      <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
        <% if user_signed_in? %>
          <%= link_to "Sign out", destroy_user_session_path, data: {"turbo-method": :delete },  class: "ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-orange-600 hover:bg-orange-700"%>
        <% else %>
        <%= link_to "Sign in", new_user_session_path,  class: "ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-orange-600 hover:bg-orange-700"%>
        <%= link_to "Sign up", new_user_registration_path,  class: "ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-orange-600 hover:bg-orange-700"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>

app/views/mainpages/homepage.html.erb
<div class="flex mt-6 max-w-7xl mx-auto px-4 sm:px-6">
  <% if current_user.present? %>
  <div class="flex-1">
  <%= link_to "Mainpage", root_path, class:"whitespace-nowrap inline-flex items-center justify-center px-2  border border-transparent rounded-md shadow-sm text-based font-medium text-white bg-orange-600 hover:bg-orange-700 mr-4"%>
  <div class="flex-1">
      <% end %>
  <div class="flex-1">
      <h2 class="text-3xl font-extrabold text-green-700">Fresh Posts: </h2>
      <% @posts.each do |post| %>
        <%= render partial: "posts/post", locals: {post: post} %>
      <% end %>
      <%= will_paginate @posts %>
  </div>

  <%= form_tag("/homepage", :method => "get") do %>
    <%= text_field_tag :post_search, params[:post_search], placeholder: "Search Posts" %>
    <%= submit_tag "Search" %>
  <% end %>

  <% if @post_search_result %>
    <% if @post_search_result.empty? %>
      <h2 class="text-1xl font-extrabold text-green-700">Post Search Results: empty </h2>
      <% elsif %>
      <h2 class="text-1xl font-extrabold text-green-700">Post Search Results: </h2>
      <%= render partial: "posts/post", collection: @post_search_result %>
    <% end %>
  <% end %>


  <%= form_tag("/homepage", :method => "get") do %>
    <%= text_field_tag :category_search, params[:category_search], placeholder: "Search Categories" %>
    <%= submit_tag "Search" %>
  <% end %>

  <% if @category_search_result %>
    <% if @category_search_result.empty? %>
      <h2 class="text-1xl font-extrabold text-green-700">Category Search Results: empty </h2>
      <% elsif %>
      <h2 class="text-1xl font-extrabold text-green-700">Category Search Results: </h2>
      <%= render partial: "categories/category", collection: @category_search_result %>
    <% end %>
  <% end %>
</div>

app/views/mainpages/index.html.erb
<% if current_user.present? %>
  <div class="relative">
    <div class="max-w-7xl mx-auto px-4 sm:px-6">
      <div class="flex justify-between items-center border-b-2 border-amber-700 py-1 md:justify-start md:space-x-10">
        <div class="flex justify-start lg:w-0 lg:flex-1 ">
  <%= link_to "Mainpage", "homepage", class:"whitespace-nowrap inline-flex items-center justify-center px-2  border border-transparent rounded-md shadow-sm text-based font-medium text-white bg-orange-600 hover:bg-orange-700 mr-4"%>
  <%= link_to "Add Category", new_category_path, class:"whitespace-nowrap inline-flex items-center justify-center px-2 py-1 border border-transparent rounded-md shadow-sm text-based font-medium text-white bg-orange-600 hover:bg-orange-700 mr-4"%>

  <%= link_to "Add Post", new_post_path, class:"whitespace-nowrap inline-flex items-center justify-center px-2  border border-transparent rounded-md shadow-sm text-based font-medium text-white bg-orange-600 hover:bg-orange-700 mr-4"%>

      </div>
    </div>
  </div>
  </div>

<% end %>

<div class="flex mt-6 max-w-7xl mx-auto px-4 sm:px-6">
  <% if current_user.present? %>
    <div class="flex-1 text-left">
      <h2 class="text-3xl font-extrabold text-green-700">Your Categories: </h2>
      <div class="grid grid-cols-1">
        <%= render partial: "categories/category", collection: current_user.categories %>
      </div>
    </div>

    <div class="flex-1">
      <div class="grid grid-cols-1 ">
        <h2 class="text-3xl font-extrabold text-green-700">Your Posts: </h2>
        <%= render partial: "posts/post", collection: @user_posts %>
      </div>
  </div>
    <div >
      <h2 class="flex-1 text-3xl font-extrabold text-green-700">User List: </h2>
      <div class="grid grid-cols-1">
        <%= render partial: "users/user", collection: @users %>
      </div>
    </div>
  <% else %>
  <div class="flex-1">
      <h2 class="text-3xl font-extrabold text-green-700">Fresh Posts: </h2>
      <%= render partial: "posts/post", collection: @new_posts %>
  </div>

  <% end %>
</div>

app/views/posts/_post.html.erb
<div>
<%= link_to post.title, post_path(post.slug), class: "text-xl text-orange-600 border-b-2 rounded border-gray-600" %>
</div>

app/views/posts/edit.html.erb
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-green-700">Edit Post</h2>
    </div>
    <div class="mt-8 space-y-6">
    <%= form_with model: @post, url: post_path(@post.slug) do |f| %>
      <div class="rounded-md shadow-sm -space-y-px">
          <%= f.text_field :title, autofocus: true, autocomplete: "title", required: true, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-sm", placeholder: "Post Title" %>
          <%= f.text_area :body, autofocus: true, required: true, class: "appearance-none rounded-none relative block w-full px-4 py-5 border border-gray-300 placeholder-gray-500 text-gray-900  focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-sm", placeholder: "Body" %>
      <%= collection_select(:post, :category_id, current_user.categories, :id, :title,{}, {class:"bg-white text-lg border-orange-500 text-green-800 rounded-b-md"} )%>

      </div>

      <div class="actions">
          <%= f.submit "Update Post", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 mt-5" %>
        </div>
      <%end%>
      </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold text-green-700">Add Post</h2>
    </div>
    <div class="mt-8 space-y-6">
    <%= form_with model: @post do |f| %>
      <div class="rounded-md shadow-sm -space-y-px">
          <%= f.text_field :title, autofocus: true, autocomplete: "title", required: true, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-sm", placeholder: "Post Title" %>
          <%= f.text_area :body, autofocus: true, required: true, class: "appearance-none rounded-none relative block w-full px-4 py-5 border border-gray-300 placeholder-gray-500 text-gray-900  focus:outline-none focus:ring-orange-500 focus:border-orange-500 focus:z-10 sm:text-sm", placeholder: "Body" %>
      <%= collection_select(:current_user, :category_id, current_user.categories, :id, :title,{}, {class:"bg-white text-lg border-orange-500 text-green-800 rounded-b-md"} )%>

      </div>

      <div class="actions">
          <%= f.submit "Create Post", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 mt-5" %>
        </div>
      <%end%>
      </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="mt-6 max-w-2xl mx-auto px-4 sm:px-6">
    <div  class="flex justify-center mb-4">
        <h2 class="text-2xl font-extrabold text-gray-900"><%= @post.title %></h2>
    </div>
    <h2 class="text-xl font-bold text-gray-700"><%= @post.body %></h2>
    <div class="flex mt-4">
      <p class="text-xl font-extrabold text-gray-900 flex-1 justify-left"> Category:
        <%= link_to @post.category.title,  category_path(@post.category.slug), class:"text-orange-600" %> </p>
      <p class="text-xl font-extrabold text-gray-900 flex-1 justify-right"><%= @post.created_at %></p>

    </div>
<div class="mt-5">
  <%= link_to "Edit Post", edit_post_path(@post.slug), class:"whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-orange-700 hover:bg-orange-900"%>
  <%= link_to "Remove Post", post_path(@post.slug), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-orange-700 hover:bg-orange-900"%>
  </div>
</div>

app/views/users/_user.html.erb
<%= link_to user.email, user_path(user), class: "text-xl text-orange-600" %>

app/views/users/show.html.erb
<h2 class="text-center text-3xl font-extrabold text-green-700">Profile: <%= @user.email %> </h2>
<div class="flex mt-6 max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex-1 text-left">
      <h2 class="text-3xl font-extrabold text-green-700">User Categories: </h2>
      <div class="grid grid-cols-1">
        <%= render partial: "categories/category", collection: @user.categories %>
      </div>
    </div>

    <div class="flex-1">
      <div class="grid grid-cols-1 ">
        <h2 class="text-3xl font-extrabold text-green-700">User Posts: </h2>
        <%= render partial: "posts/post", collection: @user.posts.order("updated_at desc") %>
      </div>
  </div>
</div>